export const districtsBiguaçu = [
  "Área Rural de Biguaçu",
  "Areias de Cima",
  "Beira Rio",
  "Boa Vista",
  "Bom Viver",
  "Cachoeiras",
  "Centro",
  "Encruzilhada",
  "Estiva",
  "Fundos",
  "Jardim Janaína",
  "Mar das Pedras",
  "Morro da Bina",
  "Prado",
  "Prado de Baixo",
  "Praia João Rosa",
  "Rio Caveiras",
  "São Miguel",
  "Saudade",
  "Saveiro",
  "Tijuquinhas",
  "Universitário",
  "Vendaval",
  // bairros informais ou localidades conhecidas
  "Sorocaba do Sul",
  "Três Riachos",
  "Alto Biguaçu",
  "Rússia",
  "Santa Catarina",
  "Santa Cruz"
];